CREATE TABLE TEST_USER( 
    SEQ INT IDENTITY(1,1) 	NOT NULL, 
    ID  VARCHAR(20) 		NOT NULL, 
    PASSWORD VARCHAR(500) 	NOT NULL, 
    NAME     VARCHAR(20) 
  CONSTRAINT PK_TEST_USER 
   PRIMARY KEY CLUSTERED (SEQ ASC) ON [PRIMARY] 
);