CREATE TABLE DB_TEST (
    SEQ        INT IDENTITY(1,1) NOT NULL, 
    TEST_TEXT  VARCHAR(300) NOT NULL, 
 CONSTRAINT PK_DB_TEST 
   PRIMARY KEY CLUSTERED (SEQ ASC) ON [PRIMARY]
) ON [PRIMARY];

INSERT INTO DB_TEST(TEST_TEXT) VALUES('테스트1');
INSERT INTO DB_TEST(TEST_TEXT) VALUES('테스트2');
INSERT INTO DB_TEST(TEST_TEXT) VALUES('테스트3');
INSERT INTO DB_TEST(TEST_TEXT) VALUES('테스트4');